---
blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/orgs/linuxmint/discussions
    about: If you have a feature request ğŸ’¡
  - name: â“ Linux Mint Forums
    url: https://forums.linuxmint.com/
    about: Please ask and answer questions here. ğŸ¥
