# -*- mode: yaml; -*-

# Default settings for galileo.py. Settings may be changed here or
# overridden using command-line switches to galileo.py.

# if in daemon mode, delay between sync runs
# specified in milliseconds
daemon-period: 15000

# keep dump files
keep-dumps: true

# upload data to Fitbit
do-upload: true

# directory to store the dumps
dump-dir: ~/.galileo

# logging (default/verbose/debug)
logging: verbose

# synchronize even if trackers were recently synchronized
force-sync: false

# trackers to include
include:
  - 123456789ABC
  - 9876543210AB
  - '112233445566' # tracker id composed of only numbers need to be quoted

# trackers to exclude
exclude:
  - AABBCCDDEEFF
  - 881144BB1234