# This is a basic workflow to help you get started with Actions

name: Validate spices and scan for safe patterns

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
    pull-requests: write

jobs:
  validate:
    name: Validate spices
    if: github.event_name != 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      # Runs a set of commands using the runners shell
      - name: Validate spices
        run: |
          sudo apt-get update -y >/dev/null 2>&1
          sudo apt-get install -y python3 python3-pil gettext >/dev/null 2>&1
          python3 validate-spice --all

  pattern-check:
    name: Pattern Check
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write

    steps:
      - name: Checkout github-actions
        uses: actions/checkout@v6
        with:
            repository: linuxmint/github-actions
            path: _github-actions

      - name: Pattern Check
        uses: ./_github-actions/pattern-checker
        with:
            github_token: ${{ github.token }}
